### ISSUE TITLE
Configuration option to use different separator in branchname

### ISSUE THREAD

**Issue by peterrus** [tstrijdhorst/tflow#10]
Currently the separator in the branch name is hardcoded to `/`. I would like to use a different character because slashes in git branch names pose some problems.

See https://coderwall.com/p/qkofma/a-caution-about-git-branch-names-with-s

**Comment by tstrijdhorst** [comment]
Thank you for bringing this to my attention I was unaware of this internal problem. Putting it on the roadmap.
